### ISSUE TITLE
reportMissingSuperCall error

### ISSUE THREAD

**Issue by akthe-at** [DetachHead/basedpyright#168]
Howdy, I have a little test script that I put random code snippets in when trying out new settings, new color schemes, LSP tweaks, etc. I opened this yesterday after installing basedpyright for the first time and noticed this diagnostic. I think that this is a mistake and that I'm not just an idiot for not knowing that it is correct. 

This diagnostic does not pop up with pyright or ruff-lsp.

![image](https://github.com/DetachHead/basedpyright/assets/105152139/3b6bc982-cc2f-4360-b097-de94a446b4e0)

**Comment by DetachHead** [comment]
this is because basedpyright enables all rules by default. this rule is kind of annoying tho, which i intend to fix in the future.

the reason you see that error on classes with no base class is because of how multiple inheritance works in python (#120). basically, there's no way to statically know whether the super call is required, so this rule enforces it everywhere. 

if you want to disable it, you can do so in your `pyproject.toml`:
```toml
[tool.basedpyright]
reportMissingSuperCall = false
```

alternatively, if you just want to disable all rules that aren't enabled by default in upstream pyright, you can set the `typeCheckingMode` to `standard`:
```toml
[tool.basedpyright]
typeCheckingMode = "standard"
```

**Comment by akthe-at** [comment]
@DetachHead Hey, I appreciate the quick feedback and the information! I think I will start with modifying the config for each item since I don't have all of the upstream vs based differences memorized yet and don't know which ones to prefer just yet! Thank You!
