### ISSUE TITLE
Unable to resolve import from the same dir

### ISSUE THREAD

**Issue by steakhutzeee** [DetachHead/basedpyright#214]
Hi,

I'm trying to figure out an issue with an import.

I have my configuration files in the root of my project and then I have a dir with the project name with source in it.

But a file is not able to import another one in that same dir. It works fine when executed, but `basedpyright` reports a `reportMissingImports`.

I tried editing my config with `include` and `extraPaths` but without luck. Why I'm not able to import correctly a module that's in the same dir?

```
(3.11.4/envs/project) ➜  source_dir git:(main) ls
__pycache__  file1.py  file2.py
```

Doing `import file2` from `file1.py` results in the error.

Thanks!

**Comment by DetachHead** [comment]
same issue as #158?

**Comment by KotlinIsland** [comment]
@steakhutzeee Yes, you have been unintentionally relying on an unsafe operation within Python where `python x.py` will add the scripts directory to the module path (`sys.path`), to demonstrate how it is unsafe, try running the script with the `-m` switch (`python -m x.y`). Basedpyright removes this "feature" for obvious reasons, but currently there is no error message explaining what is happening. See the [readme](https://github.com/DetachHead/basedpyright?tab=readme-ov-file#reporting-errors-on-invalid-relative-imports).

**Comment by steakhutzeee** [comment]
Thank you both!

I tried `import .file2` but `basedpyright` suggested to use `from . import file2`. This way it worked.

Why the first method did not work? I see it illustrated here https://github.com/DetachHead/basedpyright?tab=readme-ov-file#reporting-errors-on-invalid-relative-imports but the solution from here worked https://github.com/DetachHead/basedpyright/issues/158#issuecomment-2011016705

![Screenshot 2024-03-27 090445](https://github.com/DetachHead/basedpyright/assets/57228102/2648be50-2703-4ed9-a048-d6c95451c3a6)

**Comment by KotlinIsland** [comment]
Ah, that was an oversight in the readme, which has been corrected. Stay tuned for updates on this feature, we have some changes in the works to improve the developer experience.

**Comment by DetachHead** [comment]
closing in favor of #158 (which will be fixed by #220)

**Comment by steakhutzeee** [comment]
Running the same code that i had already fixed with `from . import file2` now results in Python saying `ImportError: attempted relative import with no known parent package`.

Any idea why?

**Comment by KotlinIsland** [comment]
Yes, it's complicated... Haha

`python foo/bar py` will add the files directory `foo` to `sys.path`, so that `import baz` (foo/baz.py) would be valid.

`python -m foo.bar` will add the __current__ directory to `sys.path`, so that `from . import baz` (or, `from foo import bar`) will work.

I would suggest that if your project is flat (all in one folder) then swap back to what you were doing before and change the config option to allow implicit relative imports. Or, to convert your project to use either: `python -m` OR make the project 'installable'(`pyproject.toml` config) and run `pip install -e .` which will make `python foo/bar.py` work properly again.

**Comment by steakhutzeee** [comment]
Thank you!

What I'm missing is why this error started appearing now :/

**Comment by KotlinIsland** [comment]
Well, this check is new in basedpyright (not sure which version), the maintainer of pyright doesn't think it's a problem.

**Comment by steakhutzeee** [comment]
Oh no i mean that the error `ImportError: attempted relative import with no known parent package` is prompted by Python directly and not by basedpyright.

**Comment by KotlinIsland** [comment]
So if you have:

foo/bar.py
```py
from . Import baz
```

When `python foo/bar.py` will add `./foo` to the module search path. So any import will look within the `foo` folder directly (`import baz` will look inside the foo folder for a file named 'baz')

But `from . Import baz` will raise an error, because python won't have understood the current module (the file 'foo/bar') as being inside a package, instead, understanding it as a solitary module, not belonging to any package. so `from .` doesn't make any sense in this scenario.
