### ISSUE TITLE
github contributors list doesn't work

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#230]
i'm assuming it's because this is a fork. maybe we should have a job that updates a contributors list or something

**Comment by KraXen72** [comment]
if you stray away with enough modification (there are some other options as well), you can open a support ticket through the github bot to detach your fork from it's original, then, only the new contributors will show up on the side, and clicking on it will show all contributors.

however, since i'm assuming you want to pull changes from upstream often, this might not be the best idea and some github ation to show contributors will work as well.

**Comment by KotlinIsland** [comment]
GitHub sucks at pulling upstream changes anyway. I think we we could just defork, then config dependabot to pull changes.

**Comment by KotlinIsland** [comment]
Maybe they will just detach your head 🤣🤣🤣

**Comment by DetachHead** [comment]
looks like we are now deforked
