### ISSUE TITLE
`typing.Union` is not deprecated

### ISSUE THREAD

**Issue by Doekeb** [DetachHead/basedpyright#242]
basedpyright reports `typing.Union` as deprecated since python 3.10. I cannot find any PEP or other documentation declaring `typing.Union` as deprecated. The relevant commit message:
>  Added a new configuration option deprecateTypingAliases that enables deprecation detection and reporting for symbols imported from the `typing` module that are deprecated according to PEP **[585](https://peps.python.org/pep-0585/)** and **[604](https://peps.python.org/pep-0604/)**. The option is currently disabled by default (even in strict mode) but can be enabled manually. This addresses #3598. (#5812)

- PEP [585](https://peps.python.org/pep-0585/) deprecates several container types from the `typing` library that have either a built-in replacement or one from `collections.abc`. There is no mention of `Union` here.
- PEP [604](https://peps.python.org/pep-0604/) introduces the `|` symbol as a shorthand for `Union` but does not deprecate `Union`.
- There is no mention of deprecation in the [docs](https://docs.python.org/3.12/library/stdtypes.html#types-union).

Moreover, though `|` is usually a more convenient shorthand, I occasionally find `Union` to be preferable stylistically, and there are some situations where it's flat-out better. These examples mainly come from long type aliases and forward references:
```python
MyBehemothOfAType: TypeAlias = (
    First
    | Second
    | Third
    | This
    | That
    | TheOtherThing
    | More
    | Less
    | ReallyLongOnes
    | EvenLongerBigOldTypes
)

MyBehemothOfAType: TypeAlias = Union[
    First,
    Second,
    Third,
    This,
    That,
    TheOtherThing,
    More,
    Less,
    ReallyLongOnes,
    EvenLongerBigOldTypes,
]
```

```python
RegularType = list[int]

MyMixedType: TypeAlias = "ForwardRef" | RegularType  # TypeError: unsupported operand type(s) for |: 'str' and 'types.GenericAlias'
MyMixedType: TypeAlias = "ForwardRef | RegularType"  # Allowed but ugly
MyMixedType: TypeAlias = Union["ForwardRef", RegularType]  # Much cleaner
```

**Comment by DetachHead** [comment]
it does mention [here](https://docs.python.org/3/library/typing.html#special-forms) that the new syntax is recommended over the old syntax:

> To define a union, use e.g. `Union[int, str]` or the shorthand `int | str`. Using that shorthand is recommended.

while i'm open to deviating from upstream deprecation warnings (like i did with `typing.Callable` to `collections.abc.Callable` because the `Callable` type has nothing to do with collections), i don't think i want to do the same with the old `Union` syntax, because the new syntax just looks better in 99% of cases and is consistent with other languages like typescript.

the only reason the `Union` syntax existed in the first place was because they didn't want to introduce new syntax to the language, then they realized later that they could do it by re-using an operator that was already in the language. their whole design process seems so poorly thought out and they keep rushing to implement changes that they end up going back on in the very next release. `Union` should have never even existed imo.

in your example with `ForwardRef`s, that can be fixed in most cases by using `from __future__ import annotations` which prevents the type annotations from being evaluated at runtime, meaning you can refer to types that haven't been defined yet without causing a runtime crash:

```py
from __future__ import annotations

RegularType = list[int]

MyMixedType: TypeAlias = ForwardRef | RegularType. # no error
```

**Comment by DetachHead** [comment]
additionally, if you want you can disable these deprecations entirely:
```toml
# pyproject.toml

[tool.basedpyright]
deprecateTypingAliases = false
```
or you can keep them as deprecated but disable the diagnostic rule to report them as errors:

```toml
# pyproject.toml

[tool.basedpyright]
reportDeprecated = 'none'
```

or if you don't want any rules that aren't enabled by default in upstream pyright:

```toml
# pyproject.toml

[tool.basedpyright]
typeCheckingMode = "strict"  # or "standard" or "basic"
```

**Comment by KotlinIsland** [comment]
> the only reason the `Union` class existed
Umm, actually, `Union` is not a 'class' (instance of `type`), it is an instance of `typing._SpecialForm`, soooo

**Comment by DetachHead** [comment]
closing this for the reasons in my previous comments. if you disagree feel free to raise another issue
