### ISSUE TITLE
Basedpyright marks typing.Optional as deprecated

### ISSUE THREAD

**Issue by Shtsh** [DetachHead/basedpyright#456]
Basedpyright marks typing.Optional as deprecated

It is not deprecated even though `Type | None` is a preferable way. This error misguiding and might make person to break compatibility without any proper reason.

<img width="1077" alt="Screenshot 2024-06-27 at 17 19 33" src="https://github.com/DetachHead/basedpyright/assets/602521/c7f6ffdd-6f10-466a-ad95-47a5e8b9d149">

**Comment by DetachHead** [comment]
while i can't find any mention in the docs anywhere that `Optional` is deprecated, the general consensus seems to be that the new `| None` syntax is preferred. there's some discussion about it [here](https://discuss.python.org/t/clarification-for-pep-604-is-foo-int-none-to-replace-all-use-of-foo-optional-int/26945/6) where  one of the typeshed maintainers makes some solid arguments against using it. 

also the depreciation comes from upstream pyright, and this is a decision i agree with. but if you prefer to continue using `Optional` you can disable this error by setting `deprecateTypingAliases` to `false`.

that said, i'm not opposed to changing the behaviour if there's a good reason to do so, which i've done before because there are some deprecations i think are really stupid, such as deprecating `typing.Callable` in favor of `collections.abc.Callable` even though `Callable` has literally nothing to do with collections.

**Comment by DetachHead** [comment]
related: #242

**Comment by DetachHead** [comment]
closing for the reasons mentioned above, feel free to raise a new issue if you disagree
