### ISSUE TITLE
readonly properties should be coloured as readonly

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#529]
```py
class Foo:
    @property
    def foo(self): ...


Foo().foo # here
```
![image](https://github.com/user-attachments/assets/6238dc97-9569-4f1f-ad76-e0187ce9d46f)

**Comment by tomtomjhj** [comment]
I would like to suggest reverting this feature. The value returned by a `@property` may change without a setter, so highlighting property accesses as readonly can be misleading.

For example:
```python
class Counter:
    def __init__(self):
        self._count = 0

    @property
    def count(self) -> int:
        return self._count

    def increment(self):
        self._count += 1

c = Counter()
c.count  # "count" is highlight as readonly
```

An workaround would be to make a setter for `count` and then use it in `increment`, but this is not applicable for codes that I do not own and may break the intended encapsulation.

A proper fix would be to analyze what a property function returns and check if that can change. But I think that would be a bit too much work (and probably undecidable) for a little gain.

**Comment by KotlinIsland** [comment]
it's "read only", not "immutable"/"final"/"constant"

indeed it is true that a property without a setter is read only

**Comment by tomtomjhj** [comment]
If I understand correctly, your intended meaning of a "property" refers to the `count` attribute itself, not the underlying `_count` value, right? Well then the current behavior technically makes sense, though I'm not sure if that's useful.

> it's "read only", not "immutable"/"final"/"constant"

Since the LSP doesn't define a modifier for "immutable"/"final"/"constant", which are common concept in many languages, I think it's reasonable to use "readonly" for those properties. That said, under your interpretation of "property", any property without a setter would already be "immutable"/"final"/"constant", regardless of what value it returns. So I'm not sure I fully understand the intention behind that distinction.

One minor side note: LSP defines "property" token type, but basedpyright doesn't seem to use it for `@property` or typical attributes. Maybe I should make a new issue for this.

**Comment by DetachHead** [comment]
i've opened #1318 for this. i didn't realize lsp had a separate semantic token type for properties. i agree that it's probably better to use that instead

**Comment by DetachHead** [comment]
oh, [`readonly` is a modifier](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#semanticTokenModifiers). so for readonly properties we should continue to use the `readonly` modifier along with the `property` token type

**Comment by DetachHead** [comment]
reopening this issue because this functionality is broken. [the unit test](https://github.com/DetachHead/basedpyright/blob/aef3c64ad2d51e38d801fdf320339e3ae9414f15/packages/pyright-internal/src/tests/samples/semantic_highlighting/final.py#L4-L18) is only passing because of #1059

**Comment by KurtBoehm** [comment]
I think this works now—if not, could you provide an example where it does not? The two snippets provided earlier seem to work as intended with the most recent release.
