### ISSUE TITLE
put a cross through github issue links that are closed

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#537]

**Comment by DetachHead** [comment]
striketrough means deprecated which probably isn't right for this scenario so we would probably need a new kind of diagnostic ( kinda related: #293). on that note we need to keep in mind that we don't want new errors to appear when the user hasn't changed any code or dependencies, just because of some external factor such as an issue being closed.

also this would be quite slow as it would need to make network requests.

**Comment by KotlinIsland** [comment]
Thinking about it, this probably better as an ide plugin
