### ISSUE TITLE
Show errors inline in config files

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#562]
now we show a popup if the config is invalid, an even better experience would be If I have a config file with an invalid option, it would be really useful if errors/lints are reported in the editor/cli output.

**Comment by DetachHead** [comment]
Duplicate of #67

**Comment by KotlinIsland** [comment]
fail, i think in source errors are 10x better that popups

**Comment by DetachHead** [comment]
that would require a lot of refactoring just to figure out what line of the config file the error is on, and a bunch of other things and i dont think it's worth it.

a config file error is more severe than a diagnostic error, so i think it should appear in a more obvious way (ie. as a notification popup instead of inline on the config file. the user may not even have the config file open and may not even notice such an error which would prevent any other errors in their source code from appearing.

**Comment by KotlinIsland** [comment]
i guess if it's a lot of work and it would only be in addition to the balloons then fair enough
