### ISSUE TITLE
Disable type inference on return types

### ISSUE THREAD

**Issue by Orkunnnn** [DetachHead/basedpyright#566]
```python
def foo():
    return bar()
```
It is hard to get what foo returns. Is there a way to disable this behavior in basedpyright. It was discussed in pyright https://github.com/microsoft/pyright/issues/3013 but unfortunately got rejected.

**Comment by DetachHead** [comment]
`--verifytypes` contains this check as well as several other checks that are useful for library developers. i want to incorporate all of those into the normal type checker instead of it being a separate CLI option that needs to be run separately and isn't available in the language server, which i believe will solve this problem.

merging with #125

**Comment by beauxq** [comment]
I think it would be good to have 3 options available for what to do if a function has no annotated return type:
- infer the type
  - current behavior without `--verifytypes`
- report an error
  - what is planned in issue 125
- take that as a `-> None` annotation
  - https://github.com/python/mypy/issues/9413 and basedmypy supports this
