### ISSUE TITLE
Can't ignore reportUnreachable when typeCheckingMode == "standard"

### ISSUE THREAD

**Issue by jose-elias-alvarez** [DetachHead/basedpyright#590]
Given this script ([playground](https://basedpyright.com/?typeCheckingMode=standard&code=JYWwDg9gTgLgBAZwJ4IFCuAM0SgdANwFMoFgIA7AfWHMwjgB44AKAZgBo4BGLgSgC5UcYTgS4EMACbEouAO5RgMQswBECAMaKw8KIQCOAV2B6EcAApIYACwpxWuHnGhxyhOcQCEquAGo4qgA65Kq8cADEcGBIigDm1jD8wLHk0IQA2nqQsACq5HoAhhrWBQBGADaEALpCIshihAAeSsx8qEA)):

```python
import sys

if sys.version_info < (3, 11):
    sys.stderr.write("script requires Python 3.11 or newer!" + "\n") # pyright:ignore[reportUnreachable]
    sys.exit(1)
```

I'd expect that the code in the condition would _not_ be marked as unreachable. In fact, when `typeCheckingMode == "all"`, the code is not marked ([playground](https://basedpyright.com/?typeCheckingMode=all&code=JYWwDg9gTgLgBAZwJ4IFCuAM0SgdANwFMoFgIA7AfWHMwjgB44AKAZgBo4BGLgSgC5UcYTgS4EMACbEouAO5RgMQswBECAMaKw8KIQCOAV2B6EcAApIYACwpxWuHnGhxyhOcQCEquAGo4qgA65Kq8cADEcGBIigDm1jD8wLHk0IQA2nqQsACq5HoAhhrWBQBGADaEALpCIshihAAeSsx8qEA)).

Pyright seems to suffer from the same issue, both in standard and strict mode ([playground](https://pyright-play.net/?code=JYWwDg9gTgLgBAZwJ4IFCuAM0SgdANwFMoFgIA7AfWHMwjgB44AKAZgBo4BGLgSgC5UcYTgS4EMACbEouAO5RgMQswBECAMaKw8KIQCOAV2B6EcAApIYACwpxWuHnGhxyhOcQCEquAGo4qgA65Kq8cADEcDBIYIT8wADm5NCEQiLIYoQAHkrMfEA)), but it'd be a nice improvement if it did work here (unless I'm misunderstanding something about the setting).

**Comment by DetachHead** [comment]
i can't seem to reproduce your issue. in both those basedpyright playground links you sent, the `# pyright:ignore[reportUnreachable]` comment seems to correctly suppress the error.

(ideally you wouldn't need to suppress the error though in cases where you expect your code to be run on multiple python versions: #8)

**Comment by jose-elias-alvarez** [comment]
That's strange – on my end, this is what I see on the first playground link when I hover over the code in the condition:

![Screenshot 2024-08-18 at 11 41 30 AM](https://github.com/user-attachments/assets/30a8f4d8-4270-4f40-80bb-5e031739b8ae)

Whereas in the second link, the code is not faded out, and nothing shows on hover:

![Screenshot 2024-08-18 at 11 43 21 AM](https://github.com/user-attachments/assets/257a588a-9a12-487a-b7a3-0f08baebcc41)

Is that not the case for you? It's consistent with what I see in the editor, too.

**Comment by KotlinIsland** [comment]
@DetachHead I believe the issue is that the *unreachable* effect is applied even though a valid ignore has been applied

**Comment by DetachHead** [comment]
> I believe the issue is that the ignore in the first example is invalid, and there is no way to suppress the *unreachable* effect

weird, there seems to be some intermittent issue with the playground that prevented the unreachable diagnostic from appearing in some cases, which is why i thought both those playground links were showing the same thing. (https://github.com/DetachHead/basedpyright-playground/issues/21)

> Additionally, with `all` the *unreachable* effect is not applied at all

this is intentional and caused by #326. since `"unreachable"` is now a separate diagnostic level and an error can't be reported with multiple levels at a time.

----

as for why the `# pyright:ignore[reportUnreachable]` comment doesn't suppress diagnostics with the unreachable/deprecated/unused levels, that's probably a result of them not actually being an error but rather a "hint" displayed in the IDE. while this decision [came from upstream](https://github.com/microsoft/pylance-release/discussions/2708#discussioncomment-2603419), the way i see it, since the "hint" is not actually an error it doesn't really make sense to suppress it. i think our solution to allow users to report unreachable code as an error or turn it off entirely adequately solves this problem, but i'm open to discussion if you disagree.

you can turn off `reportUnreachable` entirely if you want by setting it to `false` or `"none"`

**Comment by jose-elias-alvarez** [comment]
Thanks for looking into it – it sounds like a complicated situation. The hint is pretty unobtrusive in VS Code, but in Neovim and Helix, it's treated the same as any other diagnostic, so it's a bit harder to ignore (it's possible to configure the editor itself to suppress it, but that's not ideal, either).

It'd be nice to tell the language server "I know you think this code is unreachable, but it's actually fine" and keep reporting other cases that haven't specifically been approved, but from my end, just turning off the rule is fine (and #8 would resolve this specific issue in an even better way). Feel free to close this!
