### ISSUE TITLE
auto-import doesn't work for most of the standard library

### ISSUE THREAD

**Issue by beauxq** [DetachHead/basedpyright#649]
auto-import doesn't work for most of the standard library

steps:
- Open a new VSCodium window.
- Create and open a new folder.
- Create and open a new `.py` file.
- (to verify that auto-imports are working for some things) type `Iterable`
  - See that auto-import suggestions appear from `typing`, `collections.abc`, `typing_extensions`
  - Choose one and press enter to see that it creates the import statement.
- Press enter again and type `math`
  - See that no auto-import suggestions appear for the `math` module.

Also not working: `time` `pathlib` `datetime` `statistics` `pprint` ... many more - most of the standard library doesn't work.
![no-auto-import-math](https://github.com/user-attachments/assets/4597f104-2fbd-4a9c-bbdb-cd7c237345fc)
![no-auto-import-sleep](https://github.com/user-attachments/assets/0ff6254b-cfe0-4c40-92bc-785212d4192d)

**Comment by DetachHead** [comment]
yeah import suggestions have always been quite unreliable for me, in both pyright and pylance

a couple things to try:
- do the import suggestion code actions have the same issue? (<kbd>Ctrl</kbd>+<kbd>.</kbd>
- if you change the `basedpyright. analysis.diagnosticMode` setting to `"workspace"` instead of `"openFilesOnly"` does it make a difference?

related: #545
