### ISSUE TITLE
Engine version discrepancy when using with AWS Sagemaker Code Editor

### ISSUE THREAD

**Issue by steven-smith-tvg** [DetachHead/basedpyright#732]
I am trying to install the extension via open-vsx.org into AWS Sagemaker's Code Editor (their VS Code web interface).  When I install it, there are problems activating the extension:

"Activating extension 'detachhead.basedpyright' failed: The language client requires VS Code version ^1.91.0 but received version 1.90.1."

The extension reports ^1.89.0 in the extension.vsixmanifest.

<Property Id="Microsoft.VisualStudio.Code.Engine" Value="^1.89.0" />

The only reference to ^1.91.0 that I can find in the .vsix is in extension/dist/extension.js:

const v = "^1.91.0";

I don't know enough about extensions to know what to do next.

Should the extension work with ^1.89.0 ?
Is AWS Sagemaker Code Editor behaving correctly?

Thank you for your help!

**Comment by DyfanJones** [comment]
+1

**Comment by DetachHead** [comment]
not sure about those error messages but it wouldn't work anyway because pyright heavily replies on the nodejs filesystem api, which is not available in the web version of vscode. we have [a browser build of the language server](https://github.com/DetachHead/basedpyright/tree/main/packages/browser-pyright) but it uses a hacky fake filesystem that will require more effort to get working in vscode

merging this with #295

**Comment by steven-smith-tvg** [comment]
Thank you @DetachHead for getting back so quickly.  It's a shame we won't be able to get it to work.  However, thank you for getting back so quickly and thank you for all the effort you have gone to creating this extension.

**Comment by grace-yiyi** [comment]
https://github.com/DetachHead/basedpyright/issues/295。When will  this web extension can be used?
