### ISSUE TITLE
nix package build is broken

### ISSUE THREAD

**Issue by kiike** [DetachHead/basedpyright#853]
I maintain basedpyright for Nix. I noticed the `package-lock.json` files from the projects inside `packages` are absent since commit 609baa47ec7544d8a1854075eb2b0df29809184c. This commit breaks building on nix without extra steps, as every subpackage is expected to contain a lockfile and workspaces are not natively supported. I'd like to propose considering bringing back these files, as they provide extra reproducibility and are provided anyway by upstream. Let me know what you think and thanks for your work on basedpyright! :muscle:

**Comment by DetachHead** [comment]
i removed them because npm workspaces uses a single lockfile for all packages in the repo, and i switched from lerna to npm workspaces due to https://github.com/lerna/lerna/issues/4094. it's probably possible to switch back to lerna and work around that issue some other way, but id rather not because npm workspaces seems much better and simplifies a lot of the project config. 

i wonder if there's a way to configure workspaces to generate individual lockfiles

**Comment by kiike** [comment]
Thanks for replying so quickly. Fair enough. If you find a way to generate individual lockfiles, it'll be great. Otherwise, I can work around it by generating the lockfiles myself or copying from upstream.

**Comment by DetachHead** [comment]
fyi we have changed some npm dependencies so the upstream lockfiles will probably be slightly different

**Comment by DetachHead** [comment]
actually they all get bundled into a single file by webpack anyway so it doesn't even matter. in fact i should probably just move all the production dependencies to `devDependencies` because using a bundler means they aren't actually needed when you install the package. 

when you build the nix package does it just install basedpyright from npm or does it do the whole build process (ie. requires dev dependencies)?

**Comment by DetachHead** [comment]
> in fact i should probably just move all the production dependencies to `devDependencies` because using a bundler means they aren't actually needed when you install the package.

oh wait [this is already the case](https://www.npmjs.com/package/basedpyright?activeTab=dependencies). so you shouldn't need the `package-lock.json` file at all because the package published on npm does not have any dependencies

**Comment by kiike** [comment]
If I installed from NPM, yes, i wouldn't need the dependencies. However the package is built from source, following the convention on nixpkgs. I'll try to see if I can use the workspaces and update the issue.

**Comment by DetachHead** [comment]
is there a way to make it build from source the same way a python package manager would? for example if you install it like this with uv or pip it will build and install it using the configured [build backend](https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend) ([which is specified here](https://github.com/DetachHead/basedpyright/blob/a0d9247bb903ba24d4f6377dd717a5e21ac71a13/pyproject.toml#L48)):

```
uv pip install git+https://github.com/detachhead/basedpyright
```
since i've set up this repo to be built/installed as a python project rather than an npm project, you'd probably have better luck doing it that way if possible. otherwise i anticipate other things breaking as well, for example [the compiled builtin docstrings](https://docs.basedpyright.com/latest/benefits-over-pyright/pylance-features/#docstrings-for-compiled-builtin-modules) which get generated as part of the [python build process](https://github.com/DetachHead/basedpyright/blob/a0d9247bb903ba24d4f6377dd717a5e21ac71a13/pdm_build.py#L40), meaning they otherwise won't be included in the build if you only call the npm build scripts.

if you're wondering why i chose to set it up this way, my goal was to make it easier for python developers who aren't familiar with nodejs to contribute by allowing them to build basedpyright without ever having to install node themselves ([more info here](https://docs.basedpyright.com/latest/development/contributing/#building)). that said, i'm still open to ideas for any improvements i can make to the build process because it's quite messy

**Comment by kiike** [comment]
Thanks for elaborating on the build process. I guess making it available as a Python package is a nice QoL feature. I'll try to use pdm in that case, but I imagine npm will then break. As for ideas or improvements, I really can't say. Packaging in either language easily gets messy and in this case we're packaging for two languages now so now it's more fun.

**Comment by DetachHead** [comment]
alright, i'll leave this issue open for now but let me know if you run into any issues with the python build and i will try to help out

**Comment by kiike** [comment]
I got the build helper to use the root `package-lock.json`, and everything seems to build just fine now. Docstubs continue working, all while building "as an npm package" instead of a python one.
