### ISSUE TITLE
False positive`reportAttributeAccessIssue` in  python 3.8 for numpy 1.16.4

### ISSUE THREAD

**Issue by Jomik** [DetachHead/basedpyright#911]
I know this is a bit of a longshot and it is quite old stuff.. I am currently updating our codebase to apply linting and typechecks. One of the environments we support is very limited in the python environment, so it has to run Python 3.8 and we cannot compile a new version of numpy, so we are stuck on 1.16.4. 
The code _works_ but we get this error
`Error: "isnan" is not a known attribute of module "numpy" (reportAttributeAccessIssue)`
but `isnan` does exist on numpy 1.16.
The error is not present when we run in CI with python 3.9.

Do we have any solution to this, short of disabling that error? I would like to get the report for correct cases.

**Comment by DetachHead** [comment]
i'll need some more info to be able to investigate. im not familiar with numpy but it looks like it didn't have types in 1.16.4 and `isnan` did not appear to be defined in its [`__init__.py`](https://github.com/numpy/numpy/blob/v1.16.4/numpy/__init__.py) back then. it's probably being imported in some wacky way that pyright doesn't support.

if you arent already, maybe using [numpy-stubs](https://github.com/numpy/numpy-stubs) might help? if not all i really do is suggest updating to python 3.9, since 3.8 is now EOL anyway

**Comment by Jomik** [comment]
Oh amazing. `numpy-stubs` actually seem to solve the problem. I am able to install them from the git repo.

Thanks a lot!
Yeah - I wish we could, but it's a very closed system :/
It's for the Creality K1 3D printer, and apparently we got nearly no power there 😢 
We get 200MB ram, and that's not enough for Python 3.9 with the other stuff it has to run too, apparently it's more resource intensive..
