### ISSUE TITLE
Error notification: `File or directory "/<default workspace root>" does not exist` when opening multi-root workspace

### ISSUE THREAD

**Issue by russelldavis** [DetachHead/basedpyright#965]
To repro: open any [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) in vscode. The error does not occur in pyright.

**Comment by DetachHead** [comment]
i can't seem to reliably reproduce this, but i have seen this error before. it does happen in pyright too, but basedpyright reports errors as a language server notification instead of just silently logging them to a console that the user would never see. i made this change because many of the errors pyright logs relate to invalid config which is something that the user should be made aware of. 

as far as i can tell this one shouldn't be reported if the path contains that `"/<default workspace root>"`. i'll update it to check for that before reporting the error

**Comment by russelldavis** [comment]
Thanks! And thank you for basedpyright in general, really great to have this.
